#!/usr/bin/env python3
from walksignal import *

parser = argparse.ArgumentParser() 
group = parser.add_mutually_exclusive_group(required=True) 
group.add_argument("--combine", action="store_true") 
group.add_argument("--compare", action="store_true") 
parser.add_argument("--list", nargs='+', required=True) 
results = parser.parse_args() 

print(results.list) 
print(type(results.list)) 

if results.combine == True: 
	combine_plots(results.list) 
else: 
	compare_plots(results.list) 

