#!/usr/bin/env python3
from walksignal import *

parser = argparse.ArgumentParser() 
parser.add_argument("--reference", required=True) 
parser.add_argument("--list", nargs='+', required=True) 
results = parser.parse_args() 

print(results.list)
print(results.reference)

combine_plots(results.list, results.reference) 

