#!/usr/bin/env python3
import csv
import sys
import fileinput
import os
import glob
import pandas as pd

def process_file(filename):
    if not os.path.exists("{0}.pruned".format(filename)) and "pruned" not in filename:
        with open(filename, 'r') as f_input, open(filename + ".pruned", 'w') as f_output:
            csv_output = csv.writer(f_output, delimiter = ',')

            for row in csv.reader(f_input, delimiter = ','):
                if any(c.isdigit() for c in row[12]):
                    csv_output.writerow(row)
    else:
        print("{0} already pruned".format(filename))

if __name__ == "__main__":
    combined_csv = pd.concat([pd.read_csv(f) for f in sys.argv[1:]])
    combined_csv.to_csv("combined_data.csv", index=False, encoding='utf-8-sig')
    process_file("combined_data.csv")
