#!/usr/bin/env python3
from walksignal import *

parser = argparse.ArgumentParser() 
parser.add_argument("--reference", required=True) 
parser.add_argument("--datafile", required=True) 
results = parser.parse_args() 

print(results.datafile)
print(results.reference)

plot_positioning(results.datafile, results.reference) 

