#!/usr/bin/env python3
import walksignal as ws
import argparse
import numpy as np
import time
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

parser = argparse.ArgumentParser() 
parser.add_argument("-x","--x-axis", required=True) 
parser.add_argument("-y","--y-axis", required=True) 
parser.add_argument("--list", nargs='+', required=True) 
results = parser.parse_args()

x_array = np.array([])
y_array = np.array([])

for datafile in results.list:
    dataset = ws.data.DataSet(datafile)
    plotter = ws.plottools.SignalPlotter(dataset)
    if dataset.hash[results.x_axis] is not None:
        x_array = np.concatenate([x_array, dataset.hash[results.x_axis]])
    if dataset.hash[results.y_axis] is not None:
        y_array = np.concatenate([y_array, dataset.hash[results.y_axis]])

ws.plottools.plot_data(x_array, y_array, x_label=results.x_axis, y_label=results.y_axis, plot_title="{0} vs {1}".format(results.y_axis, results.x_axis))
