#!/usr/bin/env python3
import walksignal as ws
import argparse
import numpy as np
import time
import pandas as pd
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable

parser = argparse.ArgumentParser() 
parser.add_argument("-x","--x-axis", required=True) 
parser.add_argument("-y","--y-axis", required=True) 
parser.add_argument("--list", nargs='+', required=True) 
results = parser.parse_args()

x_array = np.array([])
y_array = np.array([])

for datafile in results.list:
          dataset = ws.walkreader.DataSet(datafile)
          plotter = ws.walkreader.SignalPlotter(dataset)
          if dataset.hash[results.x_axis] is not None:
              x_array = np.concatenate([x_array, dataset.hash[results.x_axis]])
              print(dataset.hash[results.x_axis])
          if dataset.hash[results.y_axis] is not None:
              y_array = np.concatenate([y_array, dataset.hash[results.y_axis]])

print(x_array)
print(y_array)
ws.walkplotter.plot_data(x_array, y_array)
