#!/usr/bin/env python3
import csv
import sys
import fileinput

def process_file(filename):
    with open(filename, 'r') as f_input, open(filename + ".pruned", 'w') as f_output:
        csv_output = csv.writer(f_output, delimiter = ',')

        for row in csv.reader(f_input, delimiter = ','):
            if any(c.isdigit() for c in row[12]):
                csv_output.writerow(row)
            #if row[12].isspace() is False:
            #    csv_output.writerow(row)



if __name__ == "__main__":
    for filename in sys.argv[1:]:
        process_file(filename)
