#!/usr/bin/env python3
import csv
import sys
import numpy as np
import time
import argparse
import requests
import matplotlib.patches as mpatches
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import walksignal.data as data
import walksignal.towers as towers
import walksignal.utils as utils
import walksignal.plottools as pt

parser = argparse.ArgumentParser() 
parser.add_argument("--reference", required=True) 
parser.add_argument("--dataset", required=True) 
parser.add_argument("--cellid", required=True)
parser.add_argument("--lac", required=True)
parser.add_argument("--mnc", required=True)
parser.add_argument("--mcc", required=True)
results = parser.parse_args() 

pt.plot_towerdata(results.dataset, results.reference, results.mcc, results.mnc, results.lac, results.cellid)
